export default {
  user: {
    token: "",
    session: null,
    user: null,
    mentor: null,
    isLoggingIn: false,
    isRegistring: false,
    isSendingPhoneLoginCode: false,
    isConfirmingPhoneLoginCode: false,
    isSendingPhoneVerificationCode: false,
    isConfirmingPhoneVerificationCode: false,
    isSendingForgotPasswordCode: false,
    isConfirmingForgotPasswordCode: false,
    isResettingPassword: false,
  },
  registration: {
    firstName: "",
    birthDate: "",
    gender: "",
    username: "",
    password: "",
    picture: null,
    phoneNumber: "",
  },
  inbox: {
    channels: [],
    isLoadingChannels: false,
  },
  swipe: {
    cards: [],
    likecount: 0,
    isLoadingCards: false,
    isLoadingMatch: false,
  },
};
