export const TUTORIAL = {
  // live screen
  MINIMIZED: "TUTORIAL_MINIMIZED",
  USERS: "TUTORIAL_USERS",
  KICK_BAN1: "TUTORIAL_KICK_BAN1",
  KICK_BAN2: "TUTORIAL_KICK_BAN2",

  // swipe screen
  SWIPE: "TUTORIAL_SWIPE",
  POINTER: "TUTORIAL_POINTER",
  SHOW_GENDER: "TUTORIAL_GENDER",

  // the last time you sent the sms
  SMS_LAST_TIME: "SMS_LAST_TIME",
};
